# web port
server:
  port: 8081

# log config
logging:
  config: classpath:logback.xml

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    config:
      adminAddresses: http://127.0.0.1:8080/xxl-job-admin
      appName: xxl-job-executor-example
      ip:
      port: 9999
      logPath: /data/applogs/xxl-job/jobhandler/



