

xxl.job.admin.addresses: http://127.0.0.1:8080/xxl-job-admin
xxl.job.accessToken:
xxl.job.executor.port: 8600
xxl.job.executor.logpath: /data/applogs/xxl-job/jobhandler
xxl.job.executor.logretentiondays: 30
#配置经过gateway转发路径功能
xxl.job.executor.address: http://127.0.0.1:9000/api/task/
spring:
  application:
    name: xxl-job-task
server:
  port: 8600

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
